window.Franchino = angular.module('tap.controllers', [])

Franchino.controller 'LoginCtrl', ($scope, auth, $state, store) ->

  doAuth = ->
    auth.signin {
      closable: false
      authParams: scope: 'openid offline_access'
    }
    return

  $scope.$on '$ionic.reconnectScope', ->
    doAuth()
    return
  doAuth()
  return


Franchino.controller 'IntroCtrl', ($scope, $state, $ionicSlideBoxDelegate) ->
  $scope.startApp = ->
    $state.go('app.products')

  $scope.next = ->
    $ionicSlideBoxDelegate.next()

  $scope.previous = ->
    $ionicSlideBoxDelegate.previous()


  $scope.slideChanged = (index) ->
    $scope.slideIndex = index

  return

Franchino.controller 'AppCtrl', ($scope) ->
  # With the new view caching in Ionic, Controllers are only called
  # when they are recreated or on app start, instead of every page change.
  # To listen for when this page is active (for example, to refresh data),
  # listen for the $ionicView.enter event:
  #$scope.$on('$ionicView.enter', function(e) {
  #});
  return


Franchino.controller 'DashCtrl', ($scope, $http) ->

  $scope.callApi = ->
    # Just call the API as you'd do using $http
    $http(
      url: 'http://auth0-nodejsapi-sample.herokuapp.com/secured/ping'
      method: 'GET').then (->
      alert 'We got the secured data successfully'
      return
    ), ->
      alert 'Please download the API seed so that you can call it.'
      return
    return

  return

# ---
# generated by js2coffee 2.0.4
